domiciles/applications/products/urls.py
from django.urls import path
#
from .views import AddProduct
from .views import UpdateProduct
from .views import DeleteProduct
from .views import AddCart
from .views import UpdateOrder
from .views import DeleteOrder
from .views import ProductsByClient
from .views import ConfirmBuy
from .views import SaveOrder
from .views import SoldProducts


app_name = 'products_app'

urlpatterns = [
    path('agregar-producto', AddProduct.as_view(), name='add_product'),

    path('actualizar-producto/<int:pk>/', UpdateProduct.as_view(), name='update_product'),

    path('eliminar-producto/<int:pk>/', DeleteProduct.as_view(), name='delete_product'),

    path('agregar-orden/<int:product>/<int:shop>/<int:client>', AddCart.as_view(), name='add_cart'),

    path('update_order/<int:shop>/<int:pk>', UpdateOrder.as_view(), name="update_order"),

    path('delete_order/<int:shop>/<int:pk>', DeleteOrder.as_view(), name="delete_order"),

    path('pedidos/<int:shop>/<int:client>', ProductsByClient.as_view(), name="order_client"),

    path('compra/<int:shop>/<int:client>', ConfirmBuy.as_view(), name='confirm_buy'),

    path('saveBuy/<int:shop>/<int:client>', SaveOrder.as_view(), name='save_order'),

    path('ventas/', SoldProducts.as_view(), name='sold_products'),
]

domiciles/applications/shops/urls.py
from django.urls import path

# views
from .views import Index
from .views import Register
from .views import PanelShop
from .views import UpdateShop
from .views import CartShop
from .views import ChangePassword

app_name = 'shop_app'

urlpatterns = [
    path('', Index.as_view(), name='index'),

    path('registrar-empresa', Register.as_view(), name='register'),

    path('sistema/', PanelShop.as_view(), name='panel_shop'),

    path('actualizar-datos/<int:pk>', UpdateShop.as_view(), name='update_shop'),

    path('pedidos/', CartShop.as_view(), name='cart_shop'),

    path('actualizar-contraseña', ChangePassword.as_view(), name='change_password'),
]

domiciles/applications/users/urls.py
from django.urls import path
#
from .views import Singing
from .views import Logout

app_name = 'users_app'

urlpatterns = [
    path('iniciar-sesion', Singing.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),]

domiciles/domiciles/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from applications.products.views import NotFoundView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.shops.urls')),
    path('sistema-cliente/', include('applications.clients.urls')),
    path('', include('applications.products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()

domiciles/applications/shops/models.py
from django.db import models
from django.db.models import Model
#
from applications.users.models import User
from .managers import ShopsManager


# Create your models here.
class Shop(Model):
    shop = models.CharField(max_length=50)
    nit = models.IntegerField(unique=True)
    avatar = models.ImageField(upload_to='shops', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    phone = models.CharField(max_length=10)
    address = models.CharField(max_length=70, blank=True, null=True)
    user = models.ForeignKey(User, related_name='shop_user', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = ShopsManager()

    def __str__(self):
        return f'{self.id} {self.shop}'

domiciles/applications/shops/forms.py
from django import forms
from django.forms import ModelForm
#
from .models import Shop


class ShopRegisterForm(ModelForm):
    email = forms.CharField(
        label="Correo electronico", widget=forms.EmailInput())

    password = forms.CharField(
        label="Contraseña", widget=forms.PasswordInput())

    equalPassword = forms.CharField(
        label="Confirmar Contraseña", widget=forms.PasswordInput())

    class Meta:
        model = Shop
        fields = ('shop', 'nit', 'phone')
        labels = {
            'shop': 'Nombre de la tienda',
            'phone': 'Telefono'
        }

    def clean_password(self):
        password = self.cleaned_data['password']
        if len(password) < 8 or len(password) > 12:
            self.add_error('password', 'La contraseña debe ser mayor a 8 y menor a 12 caracteres')
        return password

    def clean_equalPassword(self):
        password = self.cleaned_data['password']
        equalPassword = self.cleaned_data['equalPassword']
        if equalPassword != password:
            self.add_error('equalPassword', 'Las contraseñas no coinciden')
        return equalPassword


class ShopUpdateForm(forms.ModelForm):
    class Meta:
        model = Shop
        exclude = ('user', 'created_at', 'updated_at')
        labels = {
            'shop': 'Nombre de la tienda',
            'avatar': 'Imagen del tienda',
            'description': 'Descripcion de la tienda',
            'phone': 'Numero de telefono',
            'address': 'Direccion de la tienda'
        }
        widgets = {
            'shop': forms.TextInput(
                attrs={'class': 'form-control', 'type': 'text'}),

            'nit': forms.TextInput(
                attrs={'class': 'form-control', 'readonly': 'readonly'}),

            'description': forms.Textarea(
                attrs={'class': 'form-control', 'cols': '5', 'rows': '5'}),

            'phone': forms.TextInput(
                attrs={'class': 'form-control', 'type': 'tel'}),

            'address': forms.TextInput(
                attrs={'class': 'form-control', 'type': 'text'})
        }

    def clean_shop(self):
        shop = self.cleaned_data['shop']
        if len(shop) < 5:
            self.add_error(
                'shop', 'El nombre de la tienda debe ser mayor a 5 caracteres')
        return shop

    def clean_description(self):
        description = self.cleaned_data['description']
        if len(description) < 15:
            self.add_error('description', 'La description de la tienda debe ser mayor a 15 caracteres')
        return description

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if len(phone) < 10 or len(phone) > 10:
            self.add_error('phone', 'El telefono debe tener 10 caracteres')
        return phone

    def clean_address(self):
        address = self.cleaned_data['address']
        if len(address) < 15:
            self.add_error(
                'address', 'La direccion de la tienda debe tener 15 caracteres o mas')
        return address

domiciles/applications/shops/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import logout
from applications.clients.models import Client
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView
#
from applications.users.mixins import ShopPermisoMixin
from applications.products.models import Product
from applications.products.models import Order
from applications.users.models import User
from applications.users.models import Role
from applications.users.forms import ChangePasswordForm
from .models import Shop
from .forms import ShopRegisterForm
from .forms import ShopUpdateForm


class Index(TemplateView):
    """ view of the home page """
    template_name = 'shops/index.html'
    context_object_name = 'shops'
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search = self.request.GET.get('search', None)
        context['quantity'] = len(Shop.objects.obtain_all_shops())
        context['message'] = search
        context['shops'] = Shop.objects.obtain_all_shops_by_search(search)
        return context


class Register(FormView):
    """ Store Registration View """
    template_name = 'shops/register.html'
    form_class = ShopRegisterForm
    success_url = reverse_lazy('shop_app:register')

    def form_valid(self, form):
        rol = Role.objects.get_role(2)
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = User.objects.create_user(email=email, password=password, rol=rol)
        Shop.objects.create_enterprise(user, form)
        return super(Register, self).form_valid(form)


class PanelShop(ShopPermisoMixin, ListView):
    """ view of the panel of the shop """
    _shop: Shop
    _products: list[Product]
    template_name = 'shops/panel.html'
    login_url = reverse_lazy('users_app:logout')
    paginate_by = 50
    context_object_name = 'products'
    ordering = 'id'

    def get_queryset(self):
        search = self.request.GET.get('search', '')
        self._shop = Shop.objects.get_user(self.request.user)
        self._products = Product.objects.obtain_all_products_by_search(search, self._shop.id)
        return self._products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self._shop
        context['quantity'] = len(self._products)
        return context


class UpdateShop(ShopPermisoMixin, UpdateView):
    """ view of update of data shop """
    template_name = 'shops/update.html'
    model = Shop
    form_class = ShopUpdateForm
    success_url = reverse_lazy('shop_app:panel_shop')
    login_url = reverse_lazy('users_app:logout')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = Shop.objects.get_user(self.request.user)
        return context


class ChangePassword(ShopPermisoMixin, FormView):
    login_url = reverse_lazy('users_app:logout')
    template_name = 'shops/change_password.html'
    form_class = ChangePasswordForm
    success_url = reverse_lazy('users_app:logout')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = Shop.objects.get_user(self.request.user)
        return context

    def form_valid(self, form):
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        new_password = form.cleaned_data['new_password']
        user = self.request.user
        authenticated = authenticate(email=email, password=password)
        if authenticated:
            user.set_password(new_password)
            user.save()
        logout(self.request)
        return super(ChangePassword, self).form_valid(form)


class CartShop(ShopPermisoMixin, ListView):
    _user: None
    _clients: list[Client]
    login_url = reverse_lazy('users_app:logout')
    template_name = 'shops/cart_shop.html'
    context_object_name = 'clients'

    def get_queryset(self):
        self._user = Shop.objects.get_user(self.request.user)
        self._clients = Order.objects.get_clients_by_order(self._user)
        return self._clients

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self._user
        context['quantity'] = len(self._clients)
        return context

domiciles/templates/shops/cart_shop.html
{% extends 'baseSistema.html' %}
{% load static %}

{% block nav %}
    {% include 'includes/headerPanel.html' %}
{% endblock nav %}


{% block content %}
    
    <div class="col-md-12">
       <h2 class="text-success">Pedidos</h2>
    </div>

    <div class="col-md-12 row g-2">
        {% include 'includes/navigationShop.html' %}
        <div class="col-md-10">
            {% if quantity < 1 %}
                <div class="alert alert-success mt-0">
                    No se encontraron pedidos
                </div>
            {% endif %}

            
            {% if quantity >= 1 %}
                <div class="col-md-12 row g-2">
                    {% for client in clients %}
                        <a href="{% url 'products_app:order_client' user.id client.client.id %}" class="click col-md-5 ms-auto me-auto border border-success rounded">
                            <li class="list-group-item d-flex">
                                <img class="logo-shop mt-1 mb-1 ms-1" src="{% static 'img/avatar.png' %}" alt="">
                                <h5 class="text-success mt-auto mb-auto ms-auto me-auto">{{client.client.get_full_name}}</h5>
                            </li>
                        </a>
                    {% endfor %}   
                </div>
            {% endif %}
                
        </div>
            
    </div>

{% endblock content %}
    
    

domiciles/templates/shops/change_password.html
{% extends 'baseSistema.html' %}


{% block nav %}
    {% include 'includes/headerPanel.html' %}
{% endblock nav %}


{% block content %}
    <h2 class="text-success">Actualizar Contraseña</h2>
    <hr class="mt-1">

    <div class="col-md-12 row g-2">
	<nav class="nav d-flex col-md-2">
	    <a href="{% url 'shop_app:panel_shop' %}" class="nav-link">Regresar</a>
	</nav>
	<form class="col-md-6 ms-auto me-auto" method="post">
	    {% csrf_token %}
	    {{form.as_p}}
	    <button type="submit" class="btn btn-success">Actualizar</button>
	    
	</form>

    </div>



{% endblock content %}

domiciles/templates/shops/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="col-md-12 row g-2">
        <h2 class="mt-3 p-0 mb-0 col-md-6 text-success">Tiendas Disponibles</h2>
        <form class="d-flex ms-auto col-md-6" role="search" method="GET">
            <input class="form-control me-2" name="search" id="search" type="search" placeholder="Buscar Tienda" aria-label="Search">
            <button class="btn btn-success" type="submit">Buscar</button>
        </form>
    </div>
    <hr class="mt-1 mb-4">

    {# checking if found shops register #}
    {% if quantity < 1 %}
        <div class="alert alert-primary" role="alert">
            <i class="fa-solid fa-circle-exclamation"></i> No se encontraron tiendas registradas
        </div>
    {% endif %}
        
    {# get alls the shops founds  #}
    <div class="row g-4 col-md-12">
        {% for shop in shops  %}
            <div class="card ms-1 me-1" style="width: 18rem;">
                {% if shop.avatar %}
                    <img src="{{shop.avatar.url}}" class="card-img-top" alt="...">
                {% else %}
                    <img src="{% static 'img/shop.jpg' %}" class="card-img-top" alt="Imagen no disponible">
                {% endif %}
                    
                
                <div class="card-body">
                    <h5 class="card-title">{{shop.shop}}</h5>
                    {% if shop.description %}
                        <p class="card-text text-justify">{{shop.description}}</p>
                    {% endif %}   
                    <a href="{% url 'users_app:login' %}" class="btn btn-primary">Ir A tienda</a>
                </div>
            </div>
        {% endfor %}
    </div>
    
    {# get pagination of the shops #}   
    {% if is_paginated %}
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Atras</a></li>
                {% endif %}
                
                {% for page in pagination.page_range  %}
                    <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li> 
                {% endfor %}
                
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a></li>
                {% endif %}

            </ul>
        </nav>
    {% endif %}
        
{% endblock content %}
    

domiciles/templates/shops/panel.html
{% extends 'baseSistema.html' %}


{% block nav %}
    {% include 'includes/headerPanel.html' %}
{% endblock nav %}
    

{% block content %}
    <div class="col-md-12 row g-3">
        <h2 class="text-success col-md-5">Productos Registrados</h2>
        <form class="d-flex ms-auto col-md-5" role="search" method="GET">
            <input class="form-control me-2" name="search" id="search" type="search" placeholder="Buscar Producto" aria-label="Search">
            <button class="btn btn-success" type="submit">Buscar</button>
        </form>
	<div class="col-md-1">
	    <a href="{% url 'products_app:add_product' %}" class="btn btn-outline-success add-product" title="Agregar Producto"><i class="fa-regular fa-plus"></i></a>
	</div>
    </div>   

    <div class="col-md-12 row g-2 mt-2">
        {% include 'includes/navigationShop.html' %}
        <div class="col-md-10 row g-4 mt-0">
            
            {% if quantity < 1 %}
                <div class="alert alert-info col-md-12 mt-0">No hay productos registrados</div>
            {% endif %}

            
            {% if quantity >= 1 %}
                
                {% for product in products %}
                    <div class="card ms-3 me-3 p-0" style="width: 14rem; height:17rem">
                        <img src="{{product.avatar.url}}" class="card-img-top img-product" alt="Imagen del producto">
                        <div class="card-body">
                            <h5 class="card-title">{{product.product}}</h5>
                            <p class="card-text">
                                {% if product.description %} {{product.description}} {% endif %}
                            </p>
                            <a href="{% url 'products_app:update_product' product.id %}" class="btn btn-primary">Actualizar Producto</a>
                            </div>
                    </div>
                {% endfor %}
                    
            {% endif %}
            
            
            {% if is_paginated %}
                <nav aria-label="...">
                    <ul class="pagination">
                        
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a>
                            </li>
                        {% endif %}

                        {% for page in pagination.page_range %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="#">{{page}}</a>
                            </li>
                        {% endfor %}

                       {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
                        </li>
                       {% endif %}
                        
                    </ul>
                </nav>
            {% endif %}
                
            
        </div>

    </div>


{% endblock content %}
    

domiciles/templates/shops/register.html
{% extends 'base.html' %}



{% block content %}

    <h2 class="text-success">Registrar Tienda</h2>
    <hr class="mt-0">

    {% if message %}
        <div class="alert alert-success">{{message}}</div>
    {% endif %}
        

    <form method="post" id="form">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-sm btn-success">Registrarse</button>
    </form>
    
    <script>
        let form = document.querySelector('#form');
        form.classList.add('mt-2')
        let p = form.querySelectorAll('p');
        p.forEach( p => {
            p.classList.add('mt-3', 'col-md-12');
            let input = p.querySelector('input');
            input.classList.add('form-control')
        });

        let error = form.querySelector('.')
    </script>

{% endblock content %}
    

domiciles/templates/shops/update.html
{% extends 'baseSistema.html' %}


{% block nav %}
    {% include 'includes/headerPanel.html' %}
{% endblock nav %}


{% block content %}
    <h1 class="text-success">Actualizacion de datos</h1>
    <hr class="mt-1">
    
    <div class="col-md-12 row g-2">
	<nav class="nav flex-column col-md-2">
	    <a class="nav-link">Regresar</a>
	</nav>

	<div class="col-md-10">
	    <form class="col-md-12 ms-auto me-auto row g-2" method="post">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit" class="col-md-2 btn btn-success">Actualizar</button>
	    </form>
	</div>
    
    </div>

    <script>
	let p = document.querySelectorAll('form p')
	document.querySelector('#id_avatar').classList.add('form-control')
	document.querySelector('#avatar-clear_id').style.display = 'none'
	document.querySelector('label[for="avatar-clear_id"]').style.display = 'none'

	p.forEach(p => p.classList.add('mt-3', 'col-md-6'))
    </script>
{% endblock content %}
    
    