domiciles/applications/clients/urls.py
from django.urls import path
#
from .views import Register
from .views import PanelView
from .views import UpdateClient
from .views import ChangePassword
from .views import ListProducts
from .views import ListProductsByOrder

from applications.products.views import OrderList

app_name = 'clients_app'

urlpatterns = [
    path('registrarse/', Register.as_view(), name='register'),

    path('', PanelView.as_view(), name='panel-clients'),

    path('actualizar-datos/<int:pk>', UpdateClient.as_view(), name='update_client'),

    path('tienda/<int:pk>/', ListProducts.as_view(), name='list_products'),

    path('carrito-cliente/', OrderList.as_view(), name='list_orders'),

    path('carrito-cliente/tienda/<int:pk>/', ListProductsByOrder.as_view(), name='products_by_order'),

    path('actualizar-contraseña/', ChangePassword.as_view(), name='change_password')
]

domiciles/applications/products/urls.py
from django.urls import path
#
from .views import AddProduct
from .views import UpdateProduct
from .views import DeleteProduct
from .views import AddCart
from .views import UpdateOrder
from .views import DeleteOrder
from .views import ProductsByClient
from .views import ConfirmBuy
from .views import SaveOrder
from .views import SoldProducts


app_name = 'products_app'

urlpatterns = [
    path('agregar-producto', AddProduct.as_view(), name='add_product'),

    path('actualizar-producto/<int:pk>/', UpdateProduct.as_view(), name='update_product'),

    path('eliminar-producto/<int:pk>/', DeleteProduct.as_view(), name='delete_product'),

    path('agregar-orden/<int:product>/<int:shop>/<int:client>', AddCart.as_view(), name='add_cart'),

    path('update_order/<int:shop>/<int:pk>', UpdateOrder.as_view(), name="update_order"),

    path('delete_order/<int:shop>/<int:pk>', DeleteOrder.as_view(), name="delete_order"),

    path('pedidos/<int:shop>/<int:client>', ProductsByClient.as_view(), name="order_client"),

    path('compra/<int:shop>/<int:client>', ConfirmBuy.as_view(), name='confirm_buy'),

    path('saveBuy/<int:shop>/<int:client>', SaveOrder.as_view(), name='save_order'),

    path('ventas/', SoldProducts.as_view(), name='sold_products'),
]

domiciles/applications/shops/urls.py
from django.urls import path

# views
from .views import Index
from .views import Register
from .views import PanelShop
from .views import UpdateShop
from .views import CartShop
from .views import ChangePassword

app_name = 'shop_app'

urlpatterns = [
    path('', Index.as_view(), name='index'),

    path('registrar-empresa', Register.as_view(), name='register'),

    path('sistema/', PanelShop.as_view(), name='panel_shop'),

    path('actualizar-datos/<int:pk>', UpdateShop.as_view(), name='update_shop'),

    path('pedidos/', CartShop.as_view(), name='cart_shop'),

    path('actualizar-contraseña', ChangePassword.as_view(), name='change_password'),
]

domiciles/domiciles/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from applications.products.views import NotFoundView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.shops.urls')),
    path('sistema-cliente/', include('applications.clients.urls')),
    path('', include('applications.products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()

domiciles/applications/products/models.py
from django.db import models
#
from applications.shops.models import Shop
from applications.clients.models import Client
from .managers import ProductManager
from .managers import OrderManager


# Create your models here.
class Product(models.Model):
    product = models.CharField(max_length=50)
    description = models.TextField()
    avatar = models.ImageField(upload_to='products')
    price = models.FloatField(default=0)
    quantity = models.IntegerField(default=0)
    shop = models.ForeignKey(Shop, related_name='product_shop', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = ProductManager()

    def __str__(self):
        return f'{self.id} {self.product}'


class Order(models.Model):
    STATUS_CHOICES = (
        ('1', 'Pendiente'),
        ('2', 'Confirmada'),
        ('3', 'Vendido')
    )
    product = models.ForeignKey(Product, related_name='order_product', on_delete=models.CASCADE)
    shop = models.ForeignKey(Shop, related_name='order_shop', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='order_client', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    full_value = models.FloatField(default=0)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=1)
    date_add = models.DateField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = OrderManager()

    def __str__(self):
        return f'{self.id}'

domiciles/applications/products/forms.py
from django import forms
from django.forms import ModelForm
#
from .models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ('shop', 'created_at', 'updated_at')
        labels = {
            'product': 'Producto',
            'description': 'Descripcion del producto',
            'avatar': 'Imagen del producto',
            'price': 'Precio del producto',
            'quantity': 'Cantidad del producto'
        }
        widgets = {
            'product': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={
                'class': 'form-control', 'cols': '5', 'rows': '5'}),

            'price': forms.TextInput(attrs={'class': 'form-control'}),
            'quantity': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_product(self):
        product = self.cleaned_data['product']
        if len(product) < 5:
            self.add_error(
                'product', 'el nombre del producto debe ser mayor a 5 caracteres')

        return product

    def clean_description(self):
        description = self.cleaned_data['description']
        if len(description) < 15:
            self.add_error(
                'description', 'La descripcion del producto debe ser mayor a 15 caracteres')
        return description

    def clean_price(self):
        price = int(self.cleaned_data['price'])
        if price <= 50:
            self.add_error(
                'price', 'El precio del producto debe ser mayor a $50')
        return str(price)

    def clean_quantity(self):
        quantity = int(self.cleaned_data['quantity'])
        if quantity < 1: 
            self.add_error('quantity', 'La cantidad debe ser mayor a 0')
        return str(quantity)

domiciles/applications/products/views.py
import datetime
#
from django.views.generic.edit import FormView
from django.views.generic import UpdateView
from django.views.generic import ListView
from django.views.generic import View
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
#
from applications.shops.models import Shop
from applications.clients.models import Client
from .models import Product
from .models import Order
from .forms import ProductForm
from applications.users.mixins import ClientPermisoMixin
from applications.users.mixins import ShopPermisoMixin


# Create your views here.
class AddProduct(ShopPermisoMixin, FormView):
    template_name = "products/product.html"
    form_class = ProductForm
    success_url = reverse_lazy('products_app:add_product')
    login_url = reverse_lazy('users_app:logout')

    def get_context_data(self, **kwargs):
        shop = Shop.objects.get_user(self.request.user)
        context = super().get_context_data(**kwargs)
        context['user'] = shop
        return context

    def form_valid(self, form):
        shop = Shop.objects.get_user(self.request.user)
        Product.objects.saveProduct(shop, form)
        return super(AddProduct, self).form_valid(form)


class UpdateProduct(ShopPermisoMixin, UpdateView):
    template_name = 'products/update.html'
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('shop_app:panel_shop')
    login_url = reverse_lazy('users_app:logout')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = Shop.objects.get_user(self.request.user)
        context['product'] = Product.objects.get_product(self.kwargs['pk'])
        return context


class DeleteProduct(ShopPermisoMixin, View):
    login_url = reverse_lazy('users_app:logout')

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect:
        pk = self.kwargs['pk']
        product = Product.objects.get_product(pk=pk)
        delete = Product.objects.delete_product(product)
        return HttpResponseRedirect(reverse('shop_app:panel_shop')) if delete else HttpResponseRedirect(reverse('products_app:update_product', args=[pk]))


class AddCart(ClientPermisoMixin, View):
    login_url = reverse_lazy('shop_app:logout')

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect:
        product = Product.objects.get_product(self.kwargs['product'])
        shop = Shop.objects.get_shop_by_id(self.kwargs['shop'])
        client = Client.objects.get_client_by_id(self.kwargs['client'])
        Order.objects.add_order(product=product, shop=shop, client=client)
        return HttpResponseRedirect(reverse('clients_app:list_products', args=[self.kwargs['shop']]))


class OrderList(ClientPermisoMixin, ListView):
    _client: Client
    _orders: list[Order]
    template_name = 'orders/list.html'
    context_object_name = 'orders'

    def get_queryset(self) -> Order:
        self._client = Client.objects.get_client(self.request.user)
        search = self.request.GET.get('search', None)
        self._orders = Order.objects.get_orders_by_client(self._client, search)
        return self._orders

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self._client
        context['quantity'] = len(self._orders)
        return context


class UpdateOrder(ClientPermisoMixin, View):
    login_url = reverse_lazy('users_app:logout')

    def post(self, request, *args, **kwargs) -> HttpResponseRedirect:
        shop = self.kwargs['shop']
        pk = self.kwargs['pk']
        quantity = request.POST['quantity']
        order = Order.objects.get_order(shop, pk)
        order.quantity = quantity
        order.full_value = order.product.price * float(quantity)
        order.save()
        return HttpResponseRedirect(reverse('clients_app:products_by_order', args=[shop]))


class DeleteOrder(ClientPermisoMixin, View):
    login_url = reverse_lazy('users_app:logout')

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect:
        shop = self.kwargs['shop']
        pk = self.kwargs['pk']
        order = Order.objects.get_order(shop, pk)
        order.delete()
        return HttpResponseRedirect(reverse('clients_app:products_by_order', args=[shop]))


class ProductsByClient(ShopPermisoMixin, ListView):
    _user: Shop
    _products: Order
    _client: Client
    template_name = 'orders/listShop.html'
    login_url = reverse_lazy('users_app:logout')
    context_object_name = 'products'

    def get_queryset(self) -> Product:
        self._client = Client.objects.get_client_by_id(self.kwargs['client'])
        self._user = Shop.objects.get_data_shops(self.request.user)
        self._products = Order.objects.get_products_of_orders(self._client, self._user)
        return self._products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self._user
        context['client'] = self._client
        context['full_value'] = Order.objects.get_price_total_orders(self._client, self._user.id)
        return context


class ConfirmBuy(ClientPermisoMixin, View):
    login_url = reverse_lazy('users_app:logout')

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect:
        orders = Order.objects.update_status_buy(self.kwargs['shop'], self.kwargs['client'])
        for order in orders:
            order.status = 2
            order.save()
        return HttpResponseRedirect(reverse('clients_app:list_orders'))


class SaveOrder(ShopPermisoMixin, View):
    login_url = reverse_lazy('users_app:logout')

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect:
        client = self.kwargs['client']
        shop = self.kwargs['shop']
        orders = Order.objects.get_products_of_orders(client, shop)
        for order in orders:
            order.status = 3
            order.updated_at = datetime.datetime.now()
            # TODO: save data here
            order.save()
        return HttpResponseRedirect(reverse('products_app:sold_products'))


class SoldProducts(ShopPermisoMixin, ListView):
    _shop: Shop
    _products: Order
    login_url = reverse_lazy('users_app:logout')
    template_name = 'products/sold_products.html'
    context_object_name = 'products'
    paginate_by = 50
    ordering = 'id'
    model = "Order"

    def get_queryset(self) -> Order:
        self._shop = Shop.objects.get_user(self.request.user)
        dateSold = self.request.GET.get('date', None)
        self._products = Order.objects.get_orders_by_status_and_dateSold(self._shop, dateSold)
        return self._products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self._shop
        return context


class NotFoundView(TemplateView):
    template_name = 'not_found.html'

domiciles/templates/products/orders.html
{% extends 'baseSistema.html' %}


{% block nav %}
    {% include 'includes/headerClient.html' %}
{% endblock nav %}


{% block content %}
    
    <div class="col-md-12">
        <h1 class="text-success">Productos</h1>
    </div>

    <div class="col-md-12 row g-3 mt-2">
        <nav class="nav flex-column col-md-1 mt-0">
            <a href="{% url 'clients_app:list_orders' %}" class="nav-link ps-0">Regresar</a>
        </nav>
        <div class="col-md-8 mt-0 ms-auto me-auto">

            <ul class="list-group">
                {% for product in products %}
                    <li class="list-group-item d-flex ps-1 pe-0">
                        <img class="logo-shop" src="{{product.product.avatar.url}}" alt="imagen del producto">
                        <div class="col-md-7 ms-2 row g-2">
                            <h5 class="text-success col-md-12"><b class="text-succes">{{product.product.description}}</b></h5>
                            <p class="mb-0 col-md-5 mb-0 mt-0"><b class="text-success">Precio: </b> ${{product.product.price|floatformat:0}}</p>
                            <p class="mb-0 col-md-7 mb-0 mt-0"><b class="text-success">Cantidad disponible:</b> {{product.product.quantity}}</p>
                            <p class="mb-0 col-md-5 mb-0 mt-0"><b class="text-success">Cantidad Solicitada:</b> {{product.quantity}}</p>
                            <p class="mb-0 col-md-7 mb-0 mt-0"><b class="text-success">Total a pagar Por el producto:</b> ${{product.full_value|floatformat:0}}</p>
                        </div>
                        <div class="col-md-3 ms-auto me-3">
                            
                            {% if product.get_status_display == 'Pendiente' %}
                                <form action="{% url 'products_app:update_order' shop.id product.id %}" method="post" class="input-group mb-2 ms-auto">
                                    {% csrf_token %}
                                    <input type="number" class="form-control" name="quantity" placeholder="Agregar Cantidad" min="1" value="{{product.quantity}}" aria-label="Recipient's username" aria-describedby="button-addon2">
                                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Agregar</button>
                                </form>
                                <a href="{% url 'products_app:delete_order' shop.id product.id %}" class="btn btn-danger w-100">Eliminar</a>
                            {% endif %}
                                
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="card border-success mb-3 col-md-2 mt-0">
            <h5 class="card-header text-success ps-1">{{shop.shop}}</h5>
            <div class="card-body text-success p-1">
                <h6 class="card-title">Detalle de la compra</h6>
                <p class="card-text mb-0">Cantidad: {{quantity}}</p>
                <p class="card-text mb-o">Valor a pagar: ${{price_total|floatformat:0}}</p>
                
                {% for statu in status %}
                    {% if statu.get_status_display == 'Pendiente' %}
                        <a href="{% url 'products_app:confirm_buy' shop.id user.id %}" class="btn btn-success">Confirmar Compra</a>
                    {% endif %}
                {% endfor %}
                    
            </div>
        </div>
    </div>

    
        
{% endblock content %}
    


    

domiciles/templates/products/product.html
{% extends 'baseSistema.html' %}


{% block nav %}
    {% include 'includes/headerPanel.html' %}
{% endblock nav %}
    


{% block content %}

  <div class="card border-success mb-3 col-md-8 ms-auto me-auto">
    <div class="card-header row g-2 bg-success p-1">
      <h2 class="col-md-6 text-white">Agregar producto</h2>  
      <div class="col-md-6 d-flex justify-content-end">
        <a href="{% url 'shop_app:panel_shop' %}" class="btn btn-success">Regresar</a>
      </div>  
    </div>
    <div class="card-body text-success">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success">Registrar</button>
      </form>
    </div>
  </div>

  <script>
    document.querySelector('#id_avatar').classList.add('form-control');
    document.querySelector('#avatar-clear_id').style.display = 'none';
    document.querySelector('label[for="avatar-clear_id"]').style.display = 'none';
  </script>
    
{% endblock content %}
    

domiciles/templates/products/sold_products.html
{% extends 'baseSistema.html' %}


{% block nav %}
    {% include 'includes/headerPanel.html' %}
{% endblock nav %}


{% block content %}
    
    <h2 class="text-success">Ventas Realizadas</h2>
    
    <div class="col-md-12 row g-2">
       {% include 'includes/navigationShop.html' %}
        <div class="col-md-10">
            {# filters the sold #}
            <div class="col-md-12">
		<form method="get">
		    <div class="input-group mb-3">
			<input type="date" class="form-control" name="date" placeholder="Buscar Fecha" aria-label="Recipient's username" aria-describedby="button-addon2">
			<button class="btn btn-outline-success" type="submit" id="button-addon2">Buscar</button>
		    </div>
		</form>
	    
	    </div>

            <table class="table table-bordered border-success text-center">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Precio</th>
                        <th>Precio total</th>
			<th>Fecha De Venta</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
			<tr>
			    <td>{{ product.id }}</td>
			    <td>{{ product.product.product }}</td>
			    <td>{{ product.quantity }}</td>
			    <td>{{ product.product.price }}</td>
			    <td>{{ product.full_value }}</td>
			    <td>{{product.updated_at| date:"M d, Y"}}</td>
			</tr>
		    {% endfor %}
                </tbody> 
            </table>
	    {# TODO: make pagination #}
		{% if is_paginated %}
		    <nav aria-label="Page navigation example">
			<ul class="pagination">
			    {% if page_obj.has_previous %}
			    <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Atras</a></li>
			    {% endif %}

			    {% for page in pagination.page_range %}
				<li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
			    {% endfor %}

			    {% if page_obj.has_next %}
			    <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a></li>
			    {% endif %}
			</ul>
		    </nav>   
		{% endif %}
        </div>

       

    </div>



{% endblock content %}
    
    

domiciles/templates/products/update.html
{% extends 'baseSistema.html' %}



{% block nav %}
    {% include 'includes/headerPanel.html' %}
{% endblock nav %}



{% block content %}
    

<div class="card border-success mb-3 col-md-6 ms-auto me-auto">
    <div class="card-header text-white bg-success d-flex" >
        <h3 class="col-md-10">{{product.product}}</h3>
        <a href="{% url 'shop_app:panel_shop' %}" class="btn btn-success ms-auto">Volver</a>
    </div>
    <div class="card-body text-success">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" class="btn btn-success">Actualizar</button>
          {# Button trigger modal #}
          <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#exampleModal">
              eliminar
          </button>
        </form>
    </div>
</div>

{# Modal #}

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Eiminar {{product.product}}</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>
            ¿Desea eliminar este producto?, recuerde que al eliminar el producto se eliminara de la base de datos
        </p>
        </div>
        <div class="modal-footer">

          <a href="{% url 'products_app:delete_product' product.id %}" class="btn btn-danger">Eliminar</a>
        </div>
      </div>
    </div>
</div>


<script>
  document.querySelector('#id_avatar').classList.add('form-control');
  //document.querySelector('#avatar-clear_id').style.display = 'none';
  //document.querySelector('label[for="avatar-clear_id"]').style.display = 'none';
  //document.querySelector('label[for="id_avatar"]').style.display = 'none';
</script>
{% endblock content %}
    