domiciles/applications/clients/urls.py
from django.urls import path
#
from .views import Register
from .views import PanelView
from .views import UpdateClient
from .views import ChangePassword
from .views import ListProducts
from .views import ListProductsByOrder

from applications.products.views import OrderList

app_name = 'clients_app'

urlpatterns = [
    path('registrarse/', Register.as_view(), name='register'),

    path('', PanelView.as_view(), name='panel-clients'),

    path('actualizar-datos/<int:pk>', UpdateClient.as_view(), name='update_client'),

    path('tienda/<int:pk>/', ListProducts.as_view(), name='list_products'),

    path('carrito-cliente/', OrderList.as_view(), name='list_orders'),

    path('carrito-cliente/tienda/<int:pk>/', ListProductsByOrder.as_view(), name='products_by_order'),

    path('actualizar-contraseña/', ChangePassword.as_view(), name='change_password')
]

domiciles/applications/products/urls.py
from django.urls import path
#
from .views import AddProduct
from .views import UpdateProduct
from .views import DeleteProduct
from .views import AddCart
from .views import UpdateOrder
from .views import DeleteOrder
from .views import ProductsByClient
from .views import ConfirmBuy
from .views import SaveOrder
from .views import SoldProducts


app_name = 'products_app'

urlpatterns = [
    path('agregar-producto', AddProduct.as_view(), name='add_product'),

    path('actualizar-producto/<int:pk>/', UpdateProduct.as_view(), name='update_product'),

    path('eliminar-producto/<int:pk>/', DeleteProduct.as_view(), name='delete_product'),

    path('agregar-orden/<int:product>/<int:shop>/<int:client>', AddCart.as_view(), name='add_cart'),

    path('update_order/<int:shop>/<int:pk>', UpdateOrder.as_view(), name="update_order"),

    path('delete_order/<int:shop>/<int:pk>', DeleteOrder.as_view(), name="delete_order"),

    path('pedidos/<int:shop>/<int:client>', ProductsByClient.as_view(), name="order_client"),

    path('compra/<int:shop>/<int:client>', ConfirmBuy.as_view(), name='confirm_buy'),

    path('saveBuy/<int:shop>/<int:client>', SaveOrder.as_view(), name='save_order'),

    path('ventas/', SoldProducts.as_view(), name='sold_products'),
]

domiciles/applications/shops/urls.py
from django.urls import path

# views
from .views import Index
from .views import Register
from .views import PanelShop
from .views import UpdateShop
from .views import CartShop
from .views import ChangePassword

app_name = 'shop_app'

urlpatterns = [
    path('', Index.as_view(), name='index'),

    path('registrar-empresa', Register.as_view(), name='register'),

    path('sistema/', PanelShop.as_view(), name='panel_shop'),

    path('actualizar-datos/<int:pk>', UpdateShop.as_view(), name='update_shop'),

    path('pedidos/', CartShop.as_view(), name='cart_shop'),

    path('actualizar-contraseña', ChangePassword.as_view(), name='change_password'),
]

domiciles/domiciles/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from applications.products.views import NotFoundView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.shops.urls')),
    path('sistema-cliente/', include('applications.clients.urls')),
    path('', include('applications.products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()

domiciles/applications/products/models.py
from django.db import models
#
from applications.shops.models import Shop
from applications.clients.models import Client
from .managers import ProductManager
from .managers import OrderManager


# Create your models here.
class Product(models.Model):
    product = models.CharField(max_length=50)
    description = models.TextField()
    avatar = models.ImageField(upload_to='products')
    price = models.FloatField(default=0)
    quantity = models.IntegerField(default=0)
    shop = models.ForeignKey(Shop, related_name='product_shop', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = ProductManager()

    def __str__(self):
        return f'{self.id} {self.product}'


class Order(models.Model):
    STATUS_CHOICES = (
        ('1', 'Pendiente'),
        ('2', 'Confirmada'),
        ('3', 'Vendido')
    )
    product = models.ForeignKey(Product, related_name='order_product', on_delete=models.CASCADE)
    shop = models.ForeignKey(Shop, related_name='order_shop', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='order_client', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    full_value = models.FloatField(default=0)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=1)
    date_add = models.DateField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = OrderManager()

    def __str__(self):
        return f'{self.id}'

domiciles/templates/orders/list.html
{% extends 'baseSistema.html' %}
{% load static %}

{% block nav %}
    {% include 'includes/headerClient.html' %}
{% endblock nav %}


{% block content %}

    <div class="col-md-12 d-flex">
        <h2 class="text-success">Carrito</h2>
        <form class="d-flex ms-auto col-md-6" role="search" method="GET">
            <input class="form-control me-2" name="search" id="search" type="search" placeholder="Buscar Tienda" aria-label="Search">
            <button class="btn btn-success" type="submit">Buscar</button>
        </form>
    </div>

    <div class="col-md-12 row g-2 mt-2">
        {% include 'includes/navigation.html' %}
        <div class="col-md-10 mt-0">
            
            {% if quantity < 1 %}
                <div class="col-md-12 alert alert-info">No se encontraron productos agregados al carrito</div>
            {% endif %}
            
            
            {% if quantity >= 1 %}
                
                <ul class="list-group">
                    {% for order in orders %}
                        <li class="list-group-item col-md-12 d-flex pt-0">
                            
                            {% if order.shop.avatar %}
                                <img class="col-md-3 logo-shop mt-2" src="{{order.shop.avatar.url}}" alt="logo de la tienda">
                            {% else %}
                                <img class="col-md-3 logo-shop mt-2" src="{% static 'img/shop.jpg' %}" alt="logo de la tienda">
                            {% endif %}
                            

                            <div class="col-md-8 mt-0 mt-2 ms-2">
                                <h3 class="text-success">{{order.shop.shop}}</h3>
                                <p class="mb-0 text-justify">{{order.shop.description}}</p>
                            </div>
                            <div class="col-md-2 pt-1 mt-2 ms-auto me-auto">
                                <b class="text-success mt-2">Estado: </b> {{order.get_status_display}}
                                <a href="{% url 'clients_app:products_by_order' order.shop.id %}" class="btn btn-success col-md-12 mt-3">Productos</a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                    
            {% endif %}
                

        </div>
    </div>


    
{% endblock content %}
    
    

domiciles/templates/orders/listShop.html
{% extends 'baseSistema.html' %}


{% block nav %}
    {% include 'includes/headerPanel.html' %}
{% endblock nav %}


{% block content %}
    <div class="col-md-12">
        <h3 class="text-success">Orden</h3>
    </div>    

    <div class="col-md-12 row g-3">
        <nav class="nav flex-column col-md-1 mt-0">
            <a href="{% url 'shop_app:cart_shop' %}" class="nav-link ps-0">Regresar</a>
        </nav>
        <div class="col-md-7 ms-auto me-auto">
            <ul class="list-group">
                
                {% for product in products %}
                    <li class="list-group-item d-flex">
                        
                        {% if product.product.avatar %}
                            <img class="col-md-2 logo-shop" src="{{product.product.avatar.url}}" alt="imagen del producto">
                            <div class="col-md-10 ms-2 row g-2">
                                <h5 class="text-success col-md-11">{{product.product.description}}</h5>
                                <p class="mt-0 mb-0 col-md-5"><b class="text-success">Cantidad del producto:</b> {{product.product.quantity}}</p>
                                <p class="mt-0 mb-0 col-md-6"><b class="text-success">Precio del producto:</b> ${{product.product.price | floatformat:0}}</p>
                                <p class="mt-0 mb-0 col-md-5"><b class="text-success">Cantidad Solicitada</b> {{product.quantity}}</p>
                                <p class="mt-0 mb-0 col-md-6"><b class="text-success">Precio:</b> $ {{product.full_value}}</p>
                            </div>
                        {% endif %}
                        
                    </li>
                {% endfor %}
                    
            </ul>
        </div>
        <div class="card border-success mb-4 col-md-4" style="max-height: 13rem;">
            <div class="card-header text-success">Datos de la orden</div>
            <div class="card-body text-success pb-0">
              <p class="card-text mb-0"> <b>Nombres:</b> {{client.get_full_name}}</p>
              <p class="card-text mb-0"> <b>Telefono:</b> {{client.phone}}</p>
              <p class="card-text mb-0"> <b>Direccion:</b> {% if client.address %} {{client.address}} {% endif %} </p>
            </div>
            <div class="card-header text-success pt-0 pb-0 mt-0"></div>
            <div class="card-body text-success pb-2 pt-1 d-flex">
                <p class="card-text col-md-6 mb-auto mt-auto"><b>Total a pagar:</b> ${{full_value | floatformat:0}}</p>
                <a href="{% url 'products_app:save_order' user.id client.id %}" class="btn btn-primary mb-auto ms-auto mt-auto">Guardar venta</a>
            </div>
        </div>
    </div>

{% endblock content %}
    
    