domiciles/applications/clients/urls.py
from django.urls import path
#
from .views import Register
from .views import PanelView
from .views import UpdateClient
from .views import ChangePassword
from .views import ListProducts
from .views import ListProductsByOrder

from applications.products.views import OrderList

app_name = 'clients_app'

urlpatterns = [
    path('registrarse/', Register.as_view(), name='register'),

    path('', PanelView.as_view(), name='panel-clients'),

    path('actualizar-datos/<int:pk>', UpdateClient.as_view(), name='update_client'),

    path('tienda/<int:pk>/', ListProducts.as_view(), name='list_products'),

    path('carrito-cliente/', OrderList.as_view(), name='list_orders'),

    path('carrito-cliente/tienda/<int:pk>/', ListProductsByOrder.as_view(), name='products_by_order'),

    path('actualizar-contraseña/', ChangePassword.as_view(), name='change_password')
]

domiciles/applications/products/urls.py
from django.urls import path
#
from .views import AddProduct
from .views import UpdateProduct
from .views import DeleteProduct
from .views import AddCart
from .views import UpdateOrder
from .views import DeleteOrder
from .views import ProductsByClient
from .views import ConfirmBuy
from .views import SaveOrder
from .views import SoldProducts


app_name = 'products_app'

urlpatterns = [
    path('agregar-producto', AddProduct.as_view(), name='add_product'),

    path('actualizar-producto/<int:pk>/', UpdateProduct.as_view(), name='update_product'),

    path('eliminar-producto/<int:pk>/', DeleteProduct.as_view(), name='delete_product'),

    path('agregar-orden/<int:product>/<int:shop>/<int:client>', AddCart.as_view(), name='add_cart'),

    path('update_order/<int:shop>/<int:pk>', UpdateOrder.as_view(), name="update_order"),

    path('delete_order/<int:shop>/<int:pk>', DeleteOrder.as_view(), name="delete_order"),

    path('pedidos/<int:shop>/<int:client>', ProductsByClient.as_view(), name="order_client"),

    path('compra/<int:shop>/<int:client>', ConfirmBuy.as_view(), name='confirm_buy'),

    path('saveBuy/<int:shop>/<int:client>', SaveOrder.as_view(), name='save_order'),

    path('ventas/', SoldProducts.as_view(), name='sold_products'),
]

domiciles/applications/shops/urls.py
from django.urls import path

# views
from .views import Index
from .views import Register
from .views import PanelShop
from .views import UpdateShop
from .views import CartShop
from .views import ChangePassword

app_name = 'shop_app'

urlpatterns = [
    path('', Index.as_view(), name='index'),

    path('registrar-empresa', Register.as_view(), name='register'),

    path('sistema/', PanelShop.as_view(), name='panel_shop'),

    path('actualizar-datos/<int:pk>', UpdateShop.as_view(), name='update_shop'),

    path('pedidos/', CartShop.as_view(), name='cart_shop'),

    path('actualizar-contraseña', ChangePassword.as_view(), name='change_password'),
]

domiciles/applications/users/urls.py
from django.urls import path
#
from .views import Singing
from .views import Logout

app_name = 'users_app'

urlpatterns = [
    path('iniciar-sesion', Singing.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),]

domiciles/domiciles/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from applications.products.views import NotFoundView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.shops.urls')),
    path('sistema-cliente/', include('applications.clients.urls')),
    path('', include('applications.products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()

domiciles/templates/includes/header.html
<nav class="navbar navbar-expand-lg bg-success pt-3 pb-3 ">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><h2 class="text-white ms-5">Domicilios</h2></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto me-5 mb-2 mb-lg-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Resgistro y/o Iniciar Sesion
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'clients_app:register' %}">Registrarse</a></li>
                  <li><a class="dropdown-item" href="{% url 'shop_app:register' %}">Registrar Tienda</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'users_app:login' %}">Iniciar sesion</a></li>
                </ul>
              </li>
        </ul>
      </div>
    </div>
</nav>

domiciles/templates/includes/headerClient.html
<nav class="navbar navbar-expand-lg bg-success pt-3 pb-3 ">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'clients_app:panel-clients' %}"><h2 class="text-white ms-5">Domicilios</h2></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto me-5 mb-2 mb-lg-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{user.get_full_name}}
                </a>
                <ul class="dropdown-menu">
		    <li><a class="dropdown-item" href="{% url 'clients_app:update_client' user.id %}">Actualizar Datos</a></li>
		    <li><a class="dropdown-item" href="{% url 'clients_app:change_password' %}">Cambiar Contraseña</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'users_app:logout' %}">Cerrar sesion</a></li>
                </ul>
              </li>
        </ul>
      </div>
    </div>
</nav>

domiciles/templates/includes/headerPanel.html
<nav class="navbar navbar-expand-lg bg-success pt-3 pb-3 ">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'shop_app:panel_shop' %}"><h2 class="text-white ms-5">Domicilios</h2></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto me-5 mb-2 mb-lg-0">
            <div class="rounded d-flex justify-content-end">
              {% if user.avatar %}
                <img class="logo" src="{{user.avatar.url}}" alt="logo">
              {% endif %}
            </div>
            <li class="nav-item dropdown me-4 aling-items-center mt-auto mb-auto">
              <a class="nav-link dropdown-toggle text-white mt-auto mb-auto" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{user.shop}}
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'shop_app:update_shop' user.id %}">Actualizar Datos</a></li>
		<li><a class="dropdown-item" href="{% url 'shop_app:change_password' %}">Cambiar Contraseña</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'users_app:logout' %}">Cerrar sesion</a></li>
              </ul>
            </li>
        </ul>
      </div>
    </div>
</nav>

domiciles/templates/includes/navigation.html
<nav class="nav flex-column col-md-2 mt-0">
    <a class="nav-link" href="{% url 'clients_app:panel-clients' %}">Tiendas</a>
    <a class="nav-link" href="{% url 'clients_app:list_orders' %}">Carrito</a>
  </nav>

domiciles/templates/includes/navigationShop.html
<nav class="nav flex-column col-md-2 mt-0">
    <a class="nav-link ps-0" href="{% url 'shop_app:cart_shop' %}">Pedidos</a>
    <a class="nav-link ps-0" href="{% url 'products_app:sold_products' %}">Ventas</a>
</nav>